### ISSUE TITLE
Create a new data type / column in the template and in the data to handle Relative Path

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#10]
For the next release, create a new type to complement the current Folder type.
- Possible name: RelativeFolder (or something like that for both the Label and DataLabel) (for backwards compatibility, the name 'Folder' should remain as is)

Change the Template Editor to:
- expose this new type and add it to the Template DB
- check old templates (.tdb files) as they are read in, and updatethem to add this column in (or alternately, only do this for new templates ?)
- change the tooltip of Folder to read “Name of the image’s folder as a path, beginning with the Template Folder name”
- make the tooltip of RelativeFolder to read “Name of the image’s folder as a path, relative to the Template location”

Change Timelapse to
- add this type in
- updates existing  template in the ddb as needed (NOTE: Updating SQLite schemas is a real pain, and need to ensure the column orders are in the correct place)
  -update the data table as needed (Column order needs to be added and should be in the correct place)

**Comment by saulgreenberg** [comment]
The AddCOlumn, DeleteColumn, and RenameColumn are now available in the SQLiteWrapper. However, they have not been tested within Timelapse (although they work in my external test code)

**Comment by twest820** [comment]
Pushed to feature/editor.  Add/Delete/RenameColumn not needed as existing AddColumn sufficient.

**Comment by saulgreenberg** [comment]
Hey Todd
We will need the Add/Delete/Rename column for a future fix that I plan to do, i.e., by looking for differences in the template that is being ready in vs. the template that was originally used to create the DB. Its unclear what you mean by the above comment, i.e., if you removed the new methods in your develop.

**Comment by twest820** [comment]
Please refer to ImageDatabase.cs in feature/editor and open a feature issue to track the feature described rather than tracking it through an unrelated bug.
