### ISSUE TITLE
Speed up image navigation and thumbnail display

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#105]
Related to closed issue 102

Users noticed and complained that the arrow keys were too slow compared to old Timelapse. I explained about Ctl and Shift, but they said they needed to see every image in a lengthy sequence and explained why. Their use case was more than reasonable.

 I temporarily hacked this to speed it up by doubling the Throttle  from 6 images /sec to 12 (see DesiredMaximumImageRendersPerSecond). This speeds up using the arrow keys. I tested 12 on a slow laptop, and it seems to be ok. Anything higher tends to introduce some lag. This is a tradeoff, but users said the really needed faster response on use of arrow keys.

A better way could be to detect when the arrow key is on repeat, and use BitmapCacheOption.None as well as a large thumbnail (1024). When the user lifts off, load the full size image.

**Comment by saulgreenberg** [comment]
This should actually be another issue, but...
Thumbnail loading needs to be speeded up in the various dialogs that use thumbnails. While not noticable for (say) as few thumbnails, presenting several hundred is far too slow. Note that a progress bar should be shown if number of images are large. instead...

**Comment by twest820** [comment]
Marking high pri has the quick fix applied is a showstopper regression which renders Timelapse unusable (it's clearly **NOT** OK based on WPF profiling data from performant machines and evaluation of users' ability to reliably detect features in images).  The risk associated with a 12 fps throttle may be acceptable for some users in their particular analysis scenarios but even the preferred default of 6 fps is provably sometimes too high for guaranteed safe operation under the current limitations of Timelapse's render architecture.

I think this means is the throttle needs to be user configurable.  Main question seems to me to be whether it should be a image set property (.ddb granularity) or a user configuration setting (machine granularity), though there is a case to be made for making it a .tdb property.

**Comment by saulgreenberg** [comment]
Thoughts: siding towards machine granularity as its likely machine speed that will be the main effect, and I suspect users will not want to adjust this on every new image set. However, there is an assumption that image size is reasonably the same. If the user sets the throttle  with small images and then moves to larger images, that will affect update speed.

Aside: I did do some testing on deciding on a  throttle setting, using a very old laptop (which I suspect is worse than most machines being used by end-users). The chosen throttle seems just above threshold. However, worse case seems to lead to occasional stutter vs. any crash. I should add that as soon as I released the original throttle version (before I changed the throttle value) I immediately received pushback from users who noticed the slowdown and said it was affecting their work (ie, different users had requirements that went beyond the "evaluation of users' ability to reliably detect features in images" as mentioned above). 

For now, I will add the user-configurable option at the machine level.

**Comment by saulgreenberg** [comment]
User settable image throttling now in place. 

Current default is set to 9 (halfway between Todd's 6 vs Saul's 12) but this can be altered as preferred in actual releases by resetting:
    Constants.cs, DesiredMaximumImageRendersPerSecondDefault = 9.0;  
(e.g., CascadeCarnivore may set the default to 6, while Saul may set it elsewhere for his users in his Timelapse site distribution).

While this issue is closed, it is still something to work on. Consider generating a new issue describing other solutions..
