### ISSUE TITLE
UX: HelpUserControl.xaml hardcodes the default .csv name

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#12]
Two difficulties here
1. The actual default .csv is defined in Constants.cs so the help control text should be generated from code to prevent the two getting out of sync.  (I've made a quick copy/paste to put them back in sync for the moment.)
2. If the .ddb doesn't have the default name then neither will the .csv.  The help text doesn't discuss this case and therefore may create user confusion as Timelapse will unexpectedly create or update some other .csv.

**Comment by saulgreenberg** [comment]
Done. 
Text is now naming-agnostic. 
Also added text to describe Importing
