### ISSUE TITLE
Timelapse UX: adjustment controls are hidden in dialogs if file name is long

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#121]
The various image adjustment dialogs use a horizontal layout of the format

[file name] [current value] [new value if dialog applied]

which does not wrap.  This means if the file name (or potentially the current value) is long the [new value] part gets pushed off the right side of the dialog and the user has to work around by making the dialog wider to get at the controls.  Typically this isn't a problem as trail cameras default to short file names and they're not changed.  But it is awkward as the user has to understand how the control layout is done to figure out the work around and, for new users, that might be difficult as they never get to see the adjustment controls.

Some type of wrapping or a shift to a less horizontally constrained layout wouldn't be a bad thing.

**Comment by saulgreenberg** [comment]
I agree that this can be problematic. However, it could also make the layout either really ugly looking or space-intensive (The current layout tries to be space conservative). Crafting a new layout would have to be carefully done. 

Another solution - not a great one, but one that could be a reasonable tradeoff - is to include a tooltip with every field that shows the various values in full

**Comment by saulgreenberg** [comment]
Another possible solution (suggested by Todd) is to add an on-demand scrollbar to the controls.

**Comment by twest820** [comment]
Grids configured to truncate file name if needed.
