### ISSUE TITLE
data: support datetime ordering of selected images

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#126]
Currently the image data table is always populated in the order rows are returned from the database, which is equivalent to ORDER BY Id.  This is useful in that images are kept in the order they were added to the database in, which provides a certain historical record and a natural tendency to group files in batches which are chronologically ordered both internally (due to camera file naming conventions) and from batch to batch (because files).  However, it's unhelpful when reviewing the encounter history of camera arrays as all images from one camera's service are shown, the next camera from the same service, and so on.  This makes it difficult to see how a critter appeared in the array as the images from that detection are scattered well apart.

In 2.1.0.5 this is trivially addressed with an ORDER BY DateTime.  Best workaround with current bits is a custom filter selecting only the day the detection occurred on.  But this quickly becomes a hassle to apply as it scales poorly with the number of detections.

It is likely desirable to also make the DateTime column a secondary key.

**Comment by saulgreenberg** [comment]
We could add a sort menu that contains what we think are the useful sort choices. The sort would be applied only to the files in the current filter. Possible candidates could be:
- sort by order folders and files were added (i.e., by ID) - the current default
- sort by date/time
- sort by name
- sort by folder name, then file name
- sort by folder name, then file date
- sort by file date, then folder

A possible  issue with sorting by date/time using an array of cameras is that it assumes that the cameras are synchronized.
