### ISSUE TITLE
Timelapse UX: custom filter logical operator is not persisted

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#128]
Timelapse custom filters depart from normal search behaviour by defaulting to or-ing clauses rather than and-ing.  Since the user's most recent selection is not persisted in HKCU users who expect Timelapse search to behave like any other search have to constantly keep changing the setting to and.  Persisting the setting has been discussed in the past and not adopted due to concerns marginally skilled users used to getting or might get stuck if they accidentally select and.  It is unclear, however, penalizing a general population of reasonably proficient users because a few users might make poorly controlled mouse clicks is in the best interest of the overall community.  Need to discuss offline and close one way or the other.

**Comment by saulgreenberg** [comment]
Persisting the setting is a good idea, and would mitigate the and/or issue as the knowledgeable user would only have to reset it once. However, if there is a strong feeling to change the default to 'and' instead, then that is fine too.
