### ISSUE TITLE
Images: MoveImageToBackupFolder() only backs up previously backed up images

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#14]
Problem is File.Move() is called only when File.Exists().

Also, consider using File.Copy(src, dest, true) to minimize the odds of hitting file system races.

**Comment by saulgreenberg** [comment]
The problem is that the copy works, but you still can't delete the original file if there is an access issue (as is the issue with not using the cache)

**Comment by saulgreenberg** [comment]
This was solved in another issue.
