### ISSUE TITLE
Editor: build includes unused resources

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#15]
The following files are included in the editor build but don't seem to be referenced anywhere.
1. arrow_Down_16xLG.png
2. arrow_Up_16xLG.png
3. delete_16x.ico
4. EditLabel_13239.png
5. Save_6530.png

Should they be removed or included in the UX?

Close_16xLG.png, folder_Open_16xLG.png, NewFile_6276.png, and 32x32.ico are in use.

**Comment by saulgreenberg** [comment]
These icons are now removed as they are not needed.
