### ISSUE TITLE
Current state of this project Mar 2024

### ISSUE THREAD

**Issue by abfleishman** [CascadesCarnivoreProject/Carnassial#151]
This seems like an interesting project.  Any update as to whether this project is still actively developed or being used by anyone?

**Comment by saulgreenberg** [comment]
That project was a side development of Timelapse. I’m not sure if the CascadesCarnivoreProject is still active, but Timelapse certainly is (I am the developer) and is being used around the world.
See https://saul.cpsc.ucalgary.ca/timelapse/ . Executables, source, documentation, github links, etc.

Saul Greenberg
From: Abram Fleishman ***@***.***>
Sent: March 11, 2024 12:15 PM
To: CascadesCarnivoreProject/Carnassial ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CascadesCarnivoreProject/Carnassial] Current state of this project Mar 2024 (Issue #151)

[△EXTERNAL]


This seems like an interesting project. Any update as to whether this project is still actively developed or being used by anyone?

**Comment by abfleishman** [comment]
@saulgreenberg Thanks for responding!  I was just surveying the range of software options for camera trap processing and thing one came up.  I saw it was an offshoot of TimeLapse and wanted to check if the project was still active before I spent any time looking into what it has to offer compared to timelapse.

**Comment by saulgreenberg** [comment]
For what its worth (and from my recollections of when I last saw the Carnassial), there have been significant feature additions to timelapse. Notably, it works with image recognizers, in particular Megadetector. At its simplest, you can use Megadetector (via Ecoassist – see my web site) to generate a detection file that robustly recognizes empty images, and classifies by people/wildlife/vehicles. You can import that file into Timelapse and do searches on that, e.g., to review how well it does with empties and discard them from consideration, etc. Timelapse also has tons of  facilities for rapid manual entry of data. The next version will also include folder-level metadata e.g., to allow you to associate data with sites, deployments, etc.

Cheers,
Saul

**Comment by twest820** [comment]
Depends what's meant by active. It's feature complete for our needs and the build's updated on a yearly cadence to stay on the current .NET version. I can push the .NET 8 installer as a release if you want it.

We wouldn't be maintaining Carnassial (and the repo would be archived) if it wasn't still in use.

**Comment by twest820** [comment]
Closing for to lack of response. This is a bookkeeping formality—feel free to follow up here as needed, though I've enabled discussions on the repo.
