### ISSUE TITLE
test: image markers

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#19]
Need CRUD coverage but it's not clear if the code is reachable or what future intent might be.  Markers are entwined with MetaTags on MarkableImageCanvas and the call paths such as MarkableImageCanvas.AddMetaTag() are dead code.

**Comment by twest820** [comment]
Saul, could you have a look here since you have the historical context to know what to expect?

**Comment by saulgreenberg** [comment]
Hi Todd
Just back from a ride – lots of emails (mostly issue updates). I’ll try to go through them to see if there is anything I should pass back to you in terms of info.

As for me, I may play around with the Delete code.
I’ve already added (in my own repo) some code to allow multiple deletes to be done more efficiently, and I would like to see if I can collapse the two DeleteImage(s) dialog boxes into one. Its sort of a pain doing things on my small laptop, so not sure how far I will get.

If you want to talk on skype, I’ll keep it open.
Saul
