### ISSUE TITLE
Bug to be expected when we allow add/delete/change column names in template to apply to existing data files

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#21]
At some point, we will modify timelapse so added / deleted / changed name columns will be allowable, where (after a confirmation dialog box is raised) timelapse will update the data db structure appropriately. However, this will likely introduce an error with markers , as the current code literally scans existing data fields so a deleted (and possibly renamed?) field will be flagged as an error. So something to remember when we code these changes up.

**Comment by twest820** [comment]
Saul, assigning to you as this goes with feature #42.
