### ISSUE TITLE
Remove the propagate/copy context menu from standard controls

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#22]
Remove the propagate/copy forward/copy all context menu from the Folder, RelativePath, File, Date, Time, and ImageQuality controls as they don't make much sense for those.

**Comment by twest820** [comment]
What about DeleteFlag/MarkForDeletion?  There's already special delete all handling elsewhere.

I've turned off context menu generation in DataEntryControls.Generate() for File, RelativePath, Folder, Date, and Time as part of updating the logic for RelativePath in feature/editor.

**Comment by saulgreenberg** [comment]
We want to leave the menus for delete flag/mark for deletion. For example, a user may filter on dark images, then use the above to mark all those for deletion in one operation. So you can likely close this issue as you fixed the other menus.
