### ISSUE TITLE
build: dependency checks are incomplete

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#23]
Both Timelapse and the editor do a simple probe for xcopy correctness on SQLite.dll.  This should be expanded to at least exiftool and the editor's newly added dependency on Timelapse.

It may also be desirable to check assembly versions.

**Comment by saulgreenberg** [comment]
The reason I put in this check was that some users dragged timelapse.exe out of its folder, which meant that it crashed when it tried to access functions in its dependences. This check for at least one of the dependencies meant that Timelapse could track that error and provide a message to the user asking him/her to correct it. I will add checks to the other files as it won't hurt. However, I am not sure how to check assembly versions (and its not clear that its necessary, for it would really require a user to moved dlls around for this to happen).

**Comment by saulgreenberg** [comment]
The dependency checks are completed for TImelapse (see  new class CheckDependencies in Util, and the code that references it in Timelapse). However, this check has to be added into the Timelapse Editor, as the develop branch I am using doesn't yet have the editor include Timelapse.exe as a reference (i.e., do this after the branches are merged).

**Comment by saulgreenberg** [comment]
Need to check, for the Timelapse Editor, if Microsoft.WindowsAPICodePack.dll is automatically added to the debug (and release) folder, as otherwise dependency test will fail.

**Comment by twest820** [comment]
The editor doesn't use CommonOpenFileDialog so the current code is fine..
