### ISSUE TITLE
test: XML to database conversion coverage

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#26]
Need this for complete back compat coverage.

**Comment by twest820** [comment]
Saul, assigning to you as I think you're the only one with code templates and image XML to test against.

**Comment by saulgreenberg** [comment]
Partial update:
The XML to database code has been updated to the latest template format.
I note that this xml to .tdb / .ddb conversion option is rarely, if every, used anymore: the old Timelapse templates are now several years in the past. May consider removing this entirely.

**Comment by twest820** [comment]
Legacy code removed in feature/data.
