### ISSUE TITLE
What to do when there are no images 

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#29]
Timelapse could be placed in a state where there are no images:
- when a template is opened but there are no images in that folder
- when all images and their data are deleted by the user

Currently, Timelapse does not handle this.
For the meantime, I have put in a check in DeleteImages that does not allow the user to delete all images. Once the above fix is done, we should remove that.

**Comment by twest820** [comment]
Not sure from the description what the envisioned fix is, so assigning to Saul.

**Comment by saulgreenberg** [comment]
Timelapse can still be put into a state on initial load where the user decides not to load any images, but the database is still created. This is problematic, as the user can still show the fields and type into them, which crashes the system.

**Comment by saulgreenberg** [comment]
Fixed. TImelapse now has a state where it checks to see if there are any images, and if not, puts the system in a limited state that tells the user what to do.
