### ISSUE TITLE
AreRequiredBinariesPresent - bug in TimelapseEditor

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#44]
I notice that you added MicrosoftWindowsAPICodepack.dll int the dependency list. However, when I do a fresh compile on TimelapseEditor, it fails as that file is not in the Debug folder. (But I noticed that Microsoft.WindowsAPICodePack.Shell.dll is in the debug folder). 

Since this is new, can you explain, plus how to fix (which I assume means that the dll should be automatically placed there on a fresh compile)?

I didn't pick up on this yesterday, as I realize I only compiled TImelapse, not the editor

**Comment by twest820** [comment]
[7efc084]
