### ISSUE TITLE
RelativePath does not show up in pre-existing databases, even when its checked a visible via the template

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#48]
While the RelativePath is added to the data database, it does not show up in the controls even after the template tags it to make the control visible. (Although relative path does show up in the CSV file). Not sure why it does this... Todd?

Even though this applies to old databases that were created before relative path existed, there is no reason why we should restrict the use of relative path. For example, a biologist may decide to make relative path visible and allow technicians to add other images to the database. I can't see any inconsistencies in letting them do that.

**Comment by twest820** [comment]
This is currently by design per Timelapse 2.0 behaviour.  Feature #42 tracks syncing the TemplateTable from the .tdb into the .ddb.

**Comment by saulgreenberg** [comment]
Hey Todd… since you closed this an referenced Issue 42, can you read the comment I just added there (in 42)? I don’t want to ping pong this by just opening and closing issues – I think we have a different idea of ‘normal’ behaviour of templates.

Cheers,
Saul
