### ISSUE TITLE
ImageDatabase2023 Unit test needs to be updated

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#50]
Note: this  will appear after my next update to Develop.
A change in the template .tdb structure (inclusion of RelativePath in 2nd position) leads to a failure of this test because the test (and the comparison database CarnivoreTemplate 2.0.1.5.tdb) was not constructed to handle the new structure. The unit test and the CarnivoreTemplate 2.0.1.5.tdb file needs to be modified to handle the new structure.

**Comment by twest820** [comment]
Like ImageDatabase2023, this is a backwards compatibility test.  So CarnivoreTemplate 2.0.1.5.tdb SHOULD NOT be modified.

When appropriate, test expectations certainly should be updated in conjunction with product code changes.  But if the test is now failing that suggests an update was missed in addressing issue #46.
