### ISSUE TITLE
Feature and Code Cleanup: Date / Time management

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#65]
Dates need to be cleaned up as follows:
Only allow valid dates/times to be input
- Check and disallow bad dates/times to be typed in
- Use a date / time picker control instead of a text field so that only valid dates / times can be entered 
- if a 'bad' date / time is read in from a file metadata, set it to Jan 1, 0001, 00:00:00

Consolidate the date code as its redundant and all over the place.

**Comment by twest820** [comment]
Addressed in feature/data (#80, #100).
