### ISSUE TITLE
Video image shown as black

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#69]
I have a sample set of videos sent to me by another biologist. When they are imported, they are displayed as black. I noticed the code in VideoRow.cs seems to have a fix for that, but its obviously not working on that.  I have sent the sample set to Todd so he can try it with that.

I do note that if thread.Yield is changed to Thread.Sleep(1000). it does extract the image. However, this is less than ideal as it would introduce a delay in reading in files, and its likely not guaranteed to work on a slow system.

**Comment by twest820** [comment]
Mitigated in [7c74704].

**Comment by saulgreenberg** [comment]
This does not seem to occur anymore, or at least happens rarely. Saul has investigated other apparently more efficient methods to do video frame extraction, and will produce a release with that method (ie., using a .Net wrapper around ffmpg)
