### ISSUE TITLE
build: RefreshVideoPlayerDialogWindow() and DialogVideoPlayer.IsVideo() duplicate ImageRow

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#82]
RefreshVideoPlayerDialogWindow() should call ImageRow.GetImagePath() rather than incorrectly duplicating the code and violating encapsulation.  This prevents videos from playing as the path generated is malformed and null is blindly passed for the source.

RefreshVideoPlayerDialogWindow() performs its own file check rather than looking at ImageRow.ImageQuality == ImageFilter.Missing.  This issue is systemic within Timelapse but adding more instances of the problem seems undesirable.

DialogVideoPlayer.isVideo() should be removed and ImageRow.IsVideo used.  As coded, the implementation of the IsVideo() check has several issues:
- magic cookie
- incorrect culture
- avoidable clutter

**Comment by saulgreenberg** [comment]
I will address the main comments. 
However, I don't know what you mean by the following: can you please explain so I can address them too?
- magic cookie
- incorrect culture
- avoidable clutter 
  Thanks...

**Comment by saulgreenberg** [comment]
Done (except for questions sent back to Todd regarding magic cookie / incorrect culture)
