### ISSUE TITLE
using ImageQuality == ImageFilter.Missing is not a robust check

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#85]
There are issues with using ImageQuality == ImageFilter.Missing to see of an image or video file is present.

Solutions:
-  a more robust check to see if the 'non-missing' file is indeed present
- even better: dynamically determining if the image is missing or present, and changing its image quality status accordingly (although this begs the question of whether to change it to Ok or Dark if it is present) .

The issues:
- 'Missing' can be reset by the user to  another image quality attribute even if the file is missing. Thus relying on only the 'Missing' attribute can raise an error.
- A user can delete an image via timelapse, which automatically flags it as 'missing'. However, if the user restores the image later (e.g., by copying it back to the folder), the image is still marked as missing and will not be viewable.
- More generally, ImageQuality confounds two separate things
  --> OK / Dark is about the pixel contents of a valid image
  --> Missing / Corrupted is about the ability to read and show an image
  Perhaps the idea of ImageQuality needs to be revisited, but I am not sure how to best do that now. 

Something to consider in later releases

**Comment by twest820** [comment]
Current code is well behaved around FileSelection.FileNoLongerAvailable and, as noted, users can easily make point corrections to correct the occasional image.  As such, the feature requirement here is really to offer a rescan which checks for missing files.  There's not apparent user need for this and it's easy to implement if need does arise.  So closing for now.
