### ISSUE TITLE
data: unbounded growth in backup files

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#88]
Moderate use of Timelapse generates O(100MB) of backup files per image set per month.  Should
- move away from the backup on start model as this causes read only use to generate backups 
- provide some ability to space backups out in time and by volume of edits
- automatically decimate backup files as they age out

**Comment by saulgreenberg** [comment]
Partial fix:
- now limits the number of backup files with a given extension to a given amount (set at 8 backup files), where it automatically decimates older backup files 

-csv and ddb backups are now handled separately so they are backed up selectively.

While backups on start model causes read-only use to generate backups, the effort to instrument timelapse to only generate backups after changes are made may be significant, so I am deferring this for now.
What we really need is an undo, but that's another issue entirely. .
