### ISSUE TITLE
Issues associated with the hierarchical folders

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#9]
The new multiple folders scheme allows a user to select a template in a folder without any images in it. This introduces several problems. 
1. If the folder name ‘Site’ contains the template, but stores images in subfolders Set1 and Set2, the user can just load the template with no images. If a person loads a template from a folder with no images in it, it should immediately raise a dialog asking the user to add images. If the user doesn’t, then the whole operation is cancelled (i.e., no template is loaded). Alternately, the help text should be replaced by something that tells the user to add images using the Add Images to Data File menu item.
2. Duplicate entries are created in the database if a user inadvertently adds a folder twice because LoadByScanningImageFolder() / AddImages() generates a SQL insert rather than update.  Failing the add if relative paths in the database point to the folder may be undesirable as it prevents users from reimporting if more images are added to the folder but creates also the complexity of marking images deleted when removed.
3. [fixed previously] The menu item name ‘Load Images from Folder’ doesn’t reflect the semantics of what now happens (i.e., its actually Load Template (and optionally images))
4. [fixed previously] The dialog box ‘No Images Found in the Image Set’ is displayed, which needs to be altered to tell the user to use the add images using the Add Images to Data File (I don’t like the name of that… to be consistent, we should name it something like ‘Add Images to Image Set’.
5. [duplicate of 1] The screen still shows the main help text after this operation, which looks like nothing has happened (although the template appears to be actually loaded). This is, of course, confusing. Solution?

**Comment by twest820** [comment]
5.  Duplicate entries are created in the database if a user inadvertently adds a folder twice because LoadByScanningImageFolder() / AddImages() generates a SQL insert rather than update.  Failing the add if relative paths in the database point to the folder may be undesirable as it prevents users from reimporting if more images are added to the folder but creates also the complexity of marking images deleted when removed.

**Comment by twest820** [comment]
Fixed in feature/editor and merged to origin/develop [3add18b].
